// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXT2G1jStZ2PanohWmrrcv3JBetezxHY',
    appId: '1:663917359055:web:1f74478d9ff96c230aacba',
    messagingSenderId: '663917359055',
    projectId: 'flutter-firebase-e4ce5',
    authDomain: 'flutter-firebase-e4ce5.firebaseapp.com',
    storageBucket: 'flutter-firebase-e4ce5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMaw20uNr9uNVK_z3b0fL-S-2OA_iZx4',
    appId: '1:663917359055:android:5a28afc4cd4765340aacba',
    messagingSenderId: '663917359055',
    projectId: 'flutter-firebase-e4ce5',
    storageBucket: 'flutter-firebase-e4ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7kvhHSB3fcJZOUAuGK8-b8CSRCADmY8',
    appId: '1:663917359055:ios:85ff10b3087e171b0aacba',
    messagingSenderId: '663917359055',
    projectId: 'flutter-firebase-e4ce5',
    storageBucket: 'flutter-firebase-e4ce5.firebasestorage.app',
    iosBundleId: 'stephenoutlook.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7kvhHSB3fcJZOUAuGK8-b8CSRCADmY8',
    appId: '1:663917359055:ios:85ff10b3087e171b0aacba',
    messagingSenderId: '663917359055',
    projectId: 'flutter-firebase-e4ce5',
    storageBucket: 'flutter-firebase-e4ce5.firebasestorage.app',
    iosBundleId: 'stephenoutlook.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIXT2G1jStZ2PanohWmrrcv3JBetezxHY',
    appId: '1:663917359055:web:796bdc630f8147d30aacba',
    messagingSenderId: '663917359055',
    projectId: 'flutter-firebase-e4ce5',
    authDomain: 'flutter-firebase-e4ce5.firebaseapp.com',
    storageBucket: 'flutter-firebase-e4ce5.firebasestorage.app',
  );
}
